server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskdb
    username: task_user
    password: task_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: hahn-secret-key
